resources:
  pipelines:
    sunny_bay_roastery_pipeline:
      name: sunny_bay_roastery
      catalog: ${var.catalog}
      schema: bronze
      serverless: true
      root_path: "."

      libraries:
        - glob:
            include: transformations/**
